# Generated by Django 3.2.8 on 2021-10-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_message_sent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-sent_at',)},
        ),
    ]
