# Generated by Django 3.2.8 on 2021-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
